// <auto-generated />
using System;
using GamesExchange.DataAccess.EntityFramework;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace GamesExchange.DataAccess.Migrations
{
    [DbContext(typeof(GamesExchangeDbContext))]
    [Migration("20230723145741_startDB")]
    partial class startDB
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.9")
                .HasAnnotation("Proxies:ChangeTracking", false)
                .HasAnnotation("Proxies:CheckEquality", false)
                .HasAnnotation("Proxies:LazyLoading", true)
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("GamesExchange.Model.Exchanges.Exchange", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("ExpectedReturnDate")
                        .HasColumnType("datetime2");

                    b.Property<long>("GameId")
                        .HasColumnType("bigint");

                    b.Property<long>("LocatorId")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("ReturnDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("GameId");

                    b.HasIndex("LocatorId");

                    b.ToTable("Exchanges");
                });

            modelBuilder.Entity("GamesExchange.Model.Games.Game", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<int>("Console")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("OwnerId")
                        .HasColumnType("bigint");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("ReleaseDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("Studio")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("OwnerId");

                    b.ToTable("Games");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            Console = 12,
                            Description = "The Last of Us é um jogo eletrônico de ação-aventura e sobrevivência desenvolvido pela Naughty Dog e publicado pela Sony Computer Entertainment. Foi lançado em 14 de junho de 2013 para PlayStation 3.",
                            Name = "The Last of Us",
                            OwnerId = 1L,
                            Price = 40m,
                            ReleaseDate = new DateTime(2013, 6, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Studio = 7
                        },
                        new
                        {
                            Id = 2L,
                            Console = 4,
                            Description = "Red Dead Redemption 2 é um jogo eletrônico de ação-aventura desenvolvido e publicado pela RockstarGames Games. É o terceiro título da série Red Dead e foi lançado em 26 de outubro de 2018.",
                            Name = "Red Dead Redemption 2",
                            OwnerId = 1L,
                            Price = 55m,
                            ReleaseDate = new DateTime(2018, 10, 26, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Studio = 2
                        },
                        new
                        {
                            Id = 3L,
                            Console = 3,
                            Description = "The Legend of Zelda: Breath of the Wild é um jogo eletrônico de ação-aventura desenvolvido e publicado pela Nintendo para os consoles Nintendo Switch e Wii U. É o décimo nono título da série The Legend of Zelda e foi lançado em 3 de março de 2017.",
                            Name = "The Legend of Zelda: Breath of the Wild",
                            OwnerId = 1L,
                            Price = 60m,
                            ReleaseDate = new DateTime(2017, 3, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Studio = 1
                        },
                        new
                        {
                            Id = 4L,
                            Console = 4,
                            Description = "God of War é um jogo eletrônico de ação-aventura desenvolvido pela Santa Monica Studio e publicado pela Sony Interactive Entertainment. Foi lançado em 20 de abril de 2018 para PlayStation 4.",
                            Name = "God of War",
                            OwnerId = 1L,
                            Price = 50m,
                            ReleaseDate = new DateTime(2018, 4, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Studio = 23
                        },
                        new
                        {
                            Id = 5L,
                            Console = 12,
                            Description = "Grand Theft Auto V é um jogo eletrônico de ação-aventura desenvolvido pela RockstarGames North e publicado pela RockstarGames Games. Foi lançado em 17 de setembro de 2013 para PlayStation 3 e Xbox 360, e em 18 de novembro para PlayStation 4 e Xbox One.",
                            Name = "Grand Theft Auto V",
                            OwnerId = 1L,
                            Price = 45m,
                            ReleaseDate = new DateTime(2013, 9, 17, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Studio = 2
                        },
                        new
                        {
                            Id = 6L,
                            Console = 4,
                            Description = "Dark Souls III é um jogo eletrônico de ação-aventura e RPG de ação desenvolvido pela FromSoftware e publicado pela Bandai Namco Entertainment. Foi lançado em 24 de março de 2016 para PlayStation 4, Xbox One e Microsoft Windows.",
                            Name = "Dark Souls III",
                            OwnerId = 1L,
                            Price = 35m,
                            ReleaseDate = new DateTime(2016, 3, 24, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Studio = 16
                        },
                        new
                        {
                            Id = 7L,
                            Console = 1,
                            Description = "FIFA 22 é um jogo eletrônico de simulação de futebol desenvolvido e publicado pela Electronic Arts. Foi lançado em 1 de outubro de 2021 para PlayStation 4, PlayStation 5, Xbox One, Xbox Series X/S, Nintendo Switch e Microsoft Windows.",
                            Name = "FIFA 22",
                            OwnerId = 1L,
                            Price = 55m,
                            ReleaseDate = new DateTime(2021, 10, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Studio = 3
                        },
                        new
                        {
                            Id = 8L,
                            Console = 3,
                            Description = "Super Mario Odyssey é um jogo eletrônico de plataforma desenvolvido e publicado pela Nintendo. Foi lançado em 27 de outubro de 2017 para Nintendo Switch.",
                            Name = "Super Mario Odyssey",
                            OwnerId = 1L,
                            Price = 50m,
                            ReleaseDate = new DateTime(2017, 10, 27, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Studio = 1
                        },
                        new
                        {
                            Id = 9L,
                            Console = 4,
                            Description = "Overwatch é um jogo eletrônico multijogador de tiro em primeira pessoa desenvolvido e publicado pela Blizzard Entertainment. Foi lançado em 24 de maio de 2016 para PlayStation 4, Xbox One e Microsoft Windows.",
                            Name = "Overwatch",
                            OwnerId = 1L,
                            Price = 40m,
                            ReleaseDate = new DateTime(2016, 5, 24, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Studio = 9
                        },
                        new
                        {
                            Id = 10L,
                            Console = 4,
                            Description = "Cyberpunk 2077 é um jogo eletrônico de RPG de ação desenvolvido e publicado pela CD Projekt. Foi lançado em 10 de dezembro de 2020 para PlayStation 4, Xbox One, Google Stadia e Microsoft Windows.",
                            Name = "Cyberpunk 2077",
                            OwnerId = 1L,
                            Price = 60m,
                            ReleaseDate = new DateTime(2020, 12, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Studio = 12
                        },
                        new
                        {
                            Id = 11L,
                            Console = 4,
                            Description = "Uncharted 4: A Thief's End é um jogo eletrônico de ação-aventura desenvolvido pela Naughty Dog e publicado pela Sony Interactive Entertainment. Foi lançado em 10 de maio de 2016 para PlayStation 4.",
                            Name = "Uncharted 4: A Thief's End",
                            OwnerId = 1L,
                            Price = 45m,
                            ReleaseDate = new DateTime(2016, 5, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Studio = 7
                        },
                        new
                        {
                            Id = 12L,
                            Console = 4,
                            Description = "Assassin's Creed Valhalla é um jogo eletrônico de ação-aventura e RPG desenvolvido e publicado pela Ubisoft. Foi lançado em 10 de novembro de 2020 para PlayStation 4, Xbox One, Google Stadia e Microsoft Windows.",
                            Name = "Assassin's Creed Valhalla",
                            OwnerId = 1L,
                            Price = 55m,
                            ReleaseDate = new DateTime(2020, 11, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Studio = 5
                        },
                        new
                        {
                            Id = 13L,
                            Console = 3,
                            Description = "Super Smash Bros. Ultimate é um jogo eletrônico de luta desenvolvido pela Bandai Namco Studios e Sora Ltd. e publicado pela Nintendo. Foi lançado em 7 de dezembro de 2018 para Nintendo Switch.",
                            Name = "Super Smash Bros. Ultimate",
                            OwnerId = 1L,
                            Price = 50m,
                            ReleaseDate = new DateTime(2018, 12, 7, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Studio = 1
                        },
                        new
                        {
                            Id = 14L,
                            Console = 4,
                            Description = "Bloodborne é um jogo eletrônico de ação-aventura e RPG de ação desenvolvido pela FromSoftware e publicado pela Sony Computer Entertainment. Foi lançado em 24 de março de 2015 para PlayStation 4.",
                            Name = "Bloodborne",
                            OwnerId = 1L,
                            Price = 40m,
                            ReleaseDate = new DateTime(2015, 3, 24, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Studio = 16
                        },
                        new
                        {
                            Id = 16L,
                            Console = 4,
                            Description = "Horizon Zero Dawn é um jogo eletrônico de ação-aventura desenvolvido pela Guerrilla Games e publicado pela Sony Interactive Entertainment. Foi lançado em 28 de fevereiro de 2017 para PlayStation 4, e posteriormente para Microsoft Windows.",
                            Name = "Horizon Zero Dawn",
                            OwnerId = 1L,
                            Price = 50m,
                            ReleaseDate = new DateTime(2017, 2, 28, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Studio = 28
                        },
                        new
                        {
                            Id = 17L,
                            Console = 4,
                            Description = "The Witcher 3: Wild Hunt é um jogo eletrônico de RPG de ação desenvolvido pela CD Projekt RED e publicado pela CD Projekt. Foi lançado em 19 de maio de 2015 para PlayStation 4, Xbox One e Microsoft Windows.",
                            Name = "The Witcher 3: Wild Hunt",
                            OwnerId = 1L,
                            Price = 55m,
                            ReleaseDate = new DateTime(2015, 5, 19, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Studio = 12
                        },
                        new
                        {
                            Id = 18L,
                            Console = 3,
                            Description = "Super Mario 3D World + Bowser's Fury é um jogo eletrônico de plataforma desenvolvido e publicado pela Nintendo. Foi lançado em 12 de fevereiro de 2021 para Nintendo Switch.",
                            Name = "Super Mario 3D World + Bowser's Fury",
                            OwnerId = 1L,
                            Price = 45m,
                            ReleaseDate = new DateTime(2021, 2, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Studio = 1
                        },
                        new
                        {
                            Id = 19L,
                            Console = 4,
                            Description = "Fortnite é um jogo eletrônico multijogador online de sobrevivência e battle royale desenvolvido e publicado pela Epic Games. Foi lançado em 25 de julho de 2017 para Microsoft Windows, macOS, PlayStation 4 e Xbox One.",
                            Name = "Fortnite",
                            OwnerId = 1L,
                            Price = 0m,
                            ReleaseDate = new DateTime(2017, 7, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Studio = 10
                        },
                        new
                        {
                            Id = 20L,
                            Console = 1,
                            Description = "Resident Evil Village é um jogo eletrônico de survival horror desenvolvido e publicado pela Capcom. Foi lançado em 7 de maio de 2021 para PlayStation 4, PlayStation 5, Xbox One, Xbox Series X/S, Google Stadia e Microsoft Windows.",
                            Name = "Resident Evil Village",
                            OwnerId = 1L,
                            Price = 50m,
                            ReleaseDate = new DateTime(2021, 5, 7, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Studio = 14
                        },
                        new
                        {
                            Id = 21L,
                            Console = 12,
                            Description = "The Elder Scrolls V: Skyrim é um jogo eletrônico de RPG de ação desenvolvido e publicado pela Bethesda Game Studios. Foi lançado em 11 de novembro de 2011 para PlayStation 3, Xbox 360 e Microsoft Windows.",
                            Name = "The Elder Scrolls V: Skyrim",
                            OwnerId = 1L,
                            Price = 40m,
                            ReleaseDate = new DateTime(2011, 11, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Studio = 11
                        },
                        new
                        {
                            Id = 22L,
                            Console = 11,
                            Description = "Super Mario Galaxy é um jogo eletrônico de plataforma desenvolvido e publicado pela Nintendo para o console Wii. Foi lançado em 1 de novembro de 2007.",
                            Name = "Super Mario Galaxy",
                            OwnerId = 1L,
                            Price = 35m,
                            ReleaseDate = new DateTime(2007, 11, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Studio = 1
                        },
                        new
                        {
                            Id = 23L,
                            Console = 3,
                            Description = "Hades é um jogo eletrônico roguelike desenvolvido e publicado pela Supergiant Games. Foi lançado em 17 de setembro de 2020 para Nintendo Switch e Microsoft Windows.",
                            Name = "Hades",
                            OwnerId = 1L,
                            Price = 25m,
                            ReleaseDate = new DateTime(2020, 9, 17, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Studio = 6
                        },
                        new
                        {
                            Id = 24L,
                            Console = 4,
                            Description = "Ghost of Tsushima é um jogo eletrônico de ação-aventura desenvolvido pela Sucker Punch Productions e publicado pela Sony Interactive Entertainment. Foi lançado em 17 de julho de 2020 para PlayStation 4.",
                            Name = "Ghost of Tsushima",
                            OwnerId = 1L,
                            Price = 50m,
                            ReleaseDate = new DateTime(2020, 7, 17, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Studio = 22
                        },
                        new
                        {
                            Id = 25L,
                            Console = 3,
                            Description = "Pokémon Sword and Shield são jogos eletrônicos de RPG desenvolvidos pela Game Freak e publicados pela The Pokémon Company e pela Nintendo. Foram lançados em 15 de novembro de 2019 para Nintendo Switch.",
                            Name = "Pokémon Sword and Shield",
                            OwnerId = 1L,
                            Price = 45m,
                            ReleaseDate = new DateTime(2019, 11, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Studio = 43
                        },
                        new
                        {
                            Id = 26L,
                            Console = 4,
                            Description = "Call of Duty: Warzone é um jogo eletrônico de battle royale gratuito desenvolvido e publicado pela Infinity Ward e pela Activision. Foi lançado em 10 de março de 2020 para PlayStation 4, Xbox One e Microsoft Windows.",
                            Name = "Call of Duty: Warzone",
                            OwnerId = 1L,
                            Price = 0m,
                            ReleaseDate = new DateTime(2020, 3, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Studio = 20
                        },
                        new
                        {
                            Id = 27L,
                            Console = 4,
                            Description = "Sekiro: Shadows Die Twice é um jogo eletrônico de ação-aventura e RPG de ação desenvolvido pela FromSoftware e publicado pela Activision. Foi lançado em 22 de março de 2019 para PlayStation 4, Xbox One e Microsoft Windows.",
                            Name = "Sekiro: Shadows Die Twice",
                            OwnerId = 1L,
                            Price = 55m,
                            ReleaseDate = new DateTime(2019, 3, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Studio = 16
                        },
                        new
                        {
                            Id = 28L,
                            Console = 3,
                            Description = "Animal Crossing: New Horizons é um jogo eletrônico de simulação de vida desenvolvido e publicado pela Nintendo. Foi lançado em 20 de março de 2020 para Nintendo Switch.",
                            Name = "Animal Crossing: New Horizons",
                            OwnerId = 1L,
                            Price = 45m,
                            ReleaseDate = new DateTime(2020, 3, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Studio = 1
                        },
                        new
                        {
                            Id = 29L,
                            Console = 4,
                            Description = "Marvel's Spider-Man é um jogo eletrônico de ação-aventura desenvolvido pela Insomniac Games e publicado pela Sony Interactive Entertainment. Foi lançado em 7 de setembro de 2018 para PlayStation 4.",
                            Name = "Marvel's Spider-Man",
                            OwnerId = 1L,
                            Price = 50m,
                            ReleaseDate = new DateTime(2018, 9, 7, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Studio = 27
                        });
                });

            modelBuilder.Entity("GamesExchange.Model.Identification.Person", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("CellNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("HasUser")
                        .HasColumnType("bit");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("People");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            CellNumber = "",
                            Email = "admin@gmail.com",
                            FirstName = "Administrator",
                            HasUser = true,
                            LastName = "Admin",
                            PhoneNumber = ""
                        });
                });

            modelBuilder.Entity("GamesExchange.Model.Identification.User", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<bool>("Active")
                        .HasColumnType("bit");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("PersonId")
                        .HasColumnType("bigint");

                    b.Property<int>("Role")
                        .HasColumnType("int");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("PersonId")
                        .IsUnique();

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            Active = true,
                            Password = "123456",
                            PersonId = 1L,
                            Role = 1,
                            Username = "admin"
                        });
                });

            modelBuilder.Entity("GamesExchange.Model.Exchanges.Exchange", b =>
                {
                    b.HasOne("GamesExchange.Model.Games.Game", "Game")
                        .WithMany("Exchanges")
                        .HasForeignKey("GameId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("GamesExchange.Model.Identification.Person", "Locator")
                        .WithMany("Exchanges")
                        .HasForeignKey("LocatorId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Game");

                    b.Navigation("Locator");
                });

            modelBuilder.Entity("GamesExchange.Model.Games.Game", b =>
                {
                    b.HasOne("GamesExchange.Model.Identification.User", "Owner")
                        .WithMany()
                        .HasForeignKey("OwnerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Owner");
                });

            modelBuilder.Entity("GamesExchange.Model.Identification.User", b =>
                {
                    b.HasOne("GamesExchange.Model.Identification.Person", "Person")
                        .WithOne("User")
                        .HasForeignKey("GamesExchange.Model.Identification.User", "PersonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Person");
                });

            modelBuilder.Entity("GamesExchange.Model.Games.Game", b =>
                {
                    b.Navigation("Exchanges");
                });

            modelBuilder.Entity("GamesExchange.Model.Identification.Person", b =>
                {
                    b.Navigation("Exchanges");

                    b.Navigation("User")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
